### ISSUE TITLE
Error when installing with installation script in WSL environment

### ISSUE THREAD

**Issue by manucert** [ISDuBA/ISDuBA#658]
When no branch name is given, the installation will fail:
`Could not find branch CERT-Bund. Aborting...`

Default "main" seems to not work. I was using `curl -O https://raw.githubusercontent.com/ISDuBA/ISDuBA/main/docs/scripts/installall.sh
`

When with -b "main" provided it worked till the startup of Keycloak.
Then I get following error on Ubuntu 24.04.1 (WSL) (this could be a local issue):

```
ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (JPA Startup Thread) FATAL: password authentication failed for user "keycloak"
2024-11-15 15:04:48,331 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: org.hibernate.exception.GenericJDBCException: unable to obtain isolated JDBC connection [FATAL: password authentication failed for user "keycloak"] [n/a]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doTheWork(JtaIsolationDelegate.java:202)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.lambda$delegateWork$3(JtaIsolationDelegate.java:91)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doInSuspendedTransaction(JtaIsolationDelegate.java:123)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.delegateWork(JtaIsolationDelegate.java:88)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:321)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:130)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:82)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
        at org.hibernate.service.ServiceRegistry.requireService(ServiceRegistry.java:68)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:52)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
        at org.hibernate.service.ServiceRegistry.requireService(ServiceRegistry.java:68)
        at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:290)
        at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:72)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:73)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:154)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:61)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "keycloak"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:711)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:213)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:268)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
        at org.postgresql.Driver.makeConnection(Driver.java:446)
        at org.postgresql.Driver.connect(Driver.java:298)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:225)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:580)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:561)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        ... 1 more

2024-11-15 15:04:48,547 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
curl: (7) Failed to connect to localhost port 9000 after 0 ms: Couldn't connect to server
```

**Comment by koplas** [comment]
The setup script failed to configure PostgreSQL correctly. The setup scripts only work on a clean Ubuntu installation. If something has already been installed or configured, it may fail. Maybe @JanHoefelmeyer can help to debug the underlying issue.

**Comment by JanHoefelmeyer** [comment]
> When no branch name is given, the installation will fail:
Could not find branch CERT-Bund. Aborting...

What was the entire function call? Not using a branch option should not be able to cause this error message, this one should be caused by e.g.

`./installall.sh --branch CERT-Bund `

without the CERT-Bund branch existing within this repository, this will fail. 

---------------------------------------------------------

For the other error, is a keycloak-server configured? If so, how and did you adjust the environment variables?

If no Keycloak was present on the system, then the scripts will set up a Keycloak 26 and a Keycloak-admin user with the ID keycloak and a randomized password which is then stored in password.txt in the docs/scripts folder.

If that hasn't been touched, then the script should be able to read the password from that file on any subsequent runs. 

*However*, if you run a keycloak server that was not set up via the installation scripts, then you have to supply the login data for the admin via the environment variables so the script can actually login to the Keycloak server, see https://github.com/ISDuBA/ISDuBA/blob/main/docs/scripts/README.md.

**Comment by manucert** [comment]
My call for the installation script was just: `./installall.sh` with no parameters on a fresh Ubuntu 24.04 (but Windows Subsystem for Linux) installation. This somehow resulted in the error with the branch name. (The device name is recognized as branch name)
I now used a server installation of ubuntu 24.04 where also the setup of keycloak worked. In WSL there is probably an issue with opening ports for keycloak, which produced this error message.

Thie issues therefore were WSL related an can be closed. Thank you.

**Comment by koplas** [comment]
This is an issue with the scripts; I opened #664 to fix parts of this issue.

**Comment by koplas** [comment]
Running `./installall.sh -b 'main'` inside a Ubuntu WSL setup works for me.
